query transactions {
  transactions{
     id
    bot {
      id
      name
    }
    coin {
      id
      name
      abbrev
    }
    coinQuantity
    contemporaryCoinPrice
    name
    transactionDateTime
    profit
  }
}
