query transactions {
  transactions{
     id
    bot {
      id
      name
    }
    coin {
      id
      name
      abbrev
    }
    coinQuantity
    contemporaryCoinPrice
    name
    transactionDateTime
    profit
  }
}

query transactionsByBot (
  $botName: String!
  ){
    TransactionsByBot: transactionsByBot (
      botName: $botName
    ){
      id
      coin {
      abbrev
      }
      quantity
      boughtPrice
      sellPrice
      currentPrice
      dateTime
      transactionProfit
      }
    }